:bulb:(#153): Adicionando página inicial (home)
fga-eps-mds/2023.2-PrintGo-FrontEnd pull request #1
Opened 2023-10-21 19:36 UTC by AntonioRangelC

## Motivação

Foi adicionada a página home e o componente botão

## Mudanças

- Nova página home
- Componente botão

## Status Checklist

- [ ] Test
- [ ] Lint
- [ ] Development

## Screenshots

![image](https://github.com/fga-eps-mds/2023.2-PrintGo-FrontEnd/assets/57496213/e30f9a48-cec7-4363-98bf-bd379f5d3290)

## Execução

npm start

- Acesse a página na url http://localhost:3000/

2023-10-21 19:58 UTC, julisous approved these changes
Revisado

2023-10-21 20:09 UTC, guilhermedfs requested changes
Além das linhas em branco, tem que arrumar o lint. Se puder dar uma olhada nisso, pf.

2023-10-21 20:09 UTC, guilhermedfs commented on src/pages/Home.js
> +
Seria melhor remover essas linhas em branco.

2023-10-21 20:09 UTC, guilhermedfs commented on src/pages/Home.js
> +
Aqui também.

2023-10-22 02:31 UTC, vitordiniz25 requested changes
Remover linhas em branco.

2023-10-22 15:05 UTC, guilhermedfs approved these changes
LGTM!

2023-10-22 15:16 UTC, merged