:racehorse: (#171) Padronizando nomes de arquivos, comentarios e clas…
fga-eps-mds/2023.2-PrintGo-FrontEnd pull request #20
Opened 2023-10-27 19:25 UTC by julisous

…snames

## Motivação

## Mudanças

- Algo que adicionou/mudou/consertou

## Status Checklist

- [ ] Test
- [ ] Lint
- [ ] Development

## Screenshots

| Before                                               | After                                                |
| ---------------------------------------------------- | ---------------------------------------------------- |

## Execução

- Acesse a página url /Home

2023-10-27 19:40 UTC, yuriAlves5 requested changes
- [x] é necessario arrumar os 2 code smell na navbar.css e navbarSimple.css
- [x] Por padrão a branch não será aprovada se o deploy não subir corretamente

2023-10-27 20:02 UTC, guilhermedfs requested changes
Deu o seguinte erro na build do front: 

Module not found: Error: Can't resolve './pages/Contato' in '/vercel/path0/src'
16:18:06.515




 

<br class="Apple-interchange-newline"> 



Module not found: Error: Can't resolve './pages/Contato' in '/vercel/path0/src'
16:18:06.515

<br class="Apple-interchange-newline">



Module not found: Error: Can't resolve './pages/Contato' in '/vercel/path0/src'
16:18:06.515

<br class="Apple-interchange-newline">

2023-10-28 00:10 UTC, guilhermedfs approved these changes
Revisado e aprovado!

2023-10-29 14:02 UTC, yuriAlves5 approved these changes
Parece de acordo

2023-10-29 14:02 UTC, merged