(#164) Página lista de impressoras
fga-eps-mds/2023.2-PrintGo-FrontEnd pull request #28
Opened 2023-11-16 11:58 UTC by AntonioRangelC

## Motivação

## Mudanças

- Foi adicionada a página de impressoras cadastradas
- Foi criado o componente de modal
- Navbar foi adicionada

- Algo que adicionou/mudou/consertou

## Status Checklist

- [ ] Test
- [ ] Lint
- [ ] Development

## Screenshots

| Before                                               | After                                                |
| ---------------------------------------------------- | ---------------------------------------------------- |

## Execução

- Acesse a página url /impressorascadastradas

2023-11-16 18:44 UTC, yuriAlves5 requested changes
O sonar se encontra com 8 code smell e 1 bug por gentilza corrigir.

2023-11-20 14:41 UTC, yuriAlves5 reviewed
Adendo de possivel refatoração no codigo.

2023-11-20 14:41 UTC, yuriAlves5 commented on src/pages/PrintersList.js
> +            <img alt="" src={Search} />
Por usar onChange na search, o botão de pesquisa fica inutilizado

2023-11-20 14:41 UTC, yuriAlves5 commented on src/components/ui/Modal.js
> +            textColor="white"
O css do button pode ficar na .css do modal, deixando o codigo mais limpo

2023-11-20 14:59 UTC, yuriAlves5 commented on src/pages/PrintersList.js
> +          ? impressora.ativada || !impressora.ativada
é possivel separar a logica de filtro em uma função, com isso melhora a legibilidade do codigo e deixa mais facil de manter

2023-11-20 14:59 UTC, yuriAlves5 commented on src/pages/PrintersList.js
> +        }).map((impressora, index) => (
é uma boa pratica ao usar a função map, utilizar a useMemo em possiveis lista de itens muito grande. Porque toda vez que a grid é atualizada a função map vai recalcular os index, então ao usar a useMemo a função map só sera atualizada se tiver mudança nos items por deixar tudo salvo na memoria.

2023-11-22 03:01 UTC, vitordiniz25 approved these changes
Revisado e aprovado!

2023-11-22 03:01 UTC, LipeAKugel commented
Revisado!

2023-11-22 03:02 UTC, LipeAKugel approved these changes

2023-11-22 03:03 UTC, merged